[package]
name = "distributed_web_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
omnipaxos_core = { git = "https://github.com/haraldng/omnipaxos" }
omnipaxos_storage = { git = "https://github.com/haraldng/omnipaxos", default-features = true } 
warp = "0.3"
parking_lot = "0.10.0"
commitlog = "0.2.0"
sled = "0.34.7"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }
